name: CI
on:
  push:
    branches:
      - main
jobs:
  run-vitest:
    name: vitest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run-vitest
        run: |
          npm install
          npm run test
